package tech.asahiart.luvia.ui

import tech.asahiart.luvia.HostSection

class UhpHostActions(
    val shown: (String) -> Unit,
    val sectionShown: (String, HostSection) -> Unit,
    val setSection: (String, HostSection) -> Unit,
    val refreshSection: (String, HostSection) -> Unit,
    val openAgent: (String, String) -> Unit,
    val closeAgent: (String) -> Unit,
    val promptAgent: (String, String) -> Unit,
    val setAgentDraft: (String, String) -> Unit,
    val sendKeys: (String, List<tech.asahiart.luvia.AgentKey>) -> Unit,
    val checkAgent: (String) -> Unit,
    val resumeAgent: (String, String) -> Unit,
    val setShowNameAgent: (String, Boolean) -> Unit,
    val setNameAgentDraft: (String, String) -> Unit,
    val nameAgent: (String) -> Unit,
    val setShowForkAgent: (String, Boolean) -> Unit,
    val setForkAgentDraft: (String, String) -> Unit,
    val forkAgent: (String) -> Unit,
    val openDiffFile: (String, String, tech.asahiart.luvia.DiffLayer?) -> Unit,
    val closeDiffFile: (String) -> Unit,
    val addNote: (String, String, tech.asahiart.luvia.ReviewLine, String, tech.asahiart.luvia.DiffLayer?) -> Unit,
    val resolveNote: (String, String) -> Unit,
    val reopenNote: (String, String) -> Unit,
    val removeNote: (String, String) -> Unit,
    val sendNotes: (String, String) -> Unit,
    val checkNotes: (String) -> Unit,
    val setNoteDraft: (String, String) -> Unit,
    val setSendTarget: (String, String?) -> Unit,
    val addTask: (String, String, List<String>) -> Unit,
    val completeTask: (String, String) -> Unit,
    val claimTask: (String, String) -> Unit,
    val deleteTask: (String, String) -> Unit,
    val checkTasks: (String) -> Unit,
    val setShowAddTask: (String, Boolean) -> Unit,
    val setCompleteTaskId: (String, String?) -> Unit,
    val setDeleteTaskId: (String, String?) -> Unit,
    val setAddTaskDraft: (String, String, String) -> Unit,
    val refreshFiles: (String) -> Unit,
    val openFile: (String, String) -> Unit,
    val revealFile: (String, String) -> Unit,
    val setSearchQuery: (String, String) -> Unit,
    val querySearch: (String) -> Unit,
    val activateSearch: (String, String) -> Unit,
    val setShowCreateWorktree: (String, Boolean) -> Unit,
    val setCreateWorktreeBranch: (String, String) -> Unit,
    val createWorktree: (String) -> Unit,
    val openWorktree: (String, String) -> Unit,
    val setRemoveWorktreePath: (String, String?) -> Unit,
    val removeWorktree: (String, String) -> Unit,
    val enableAutomation: (String, String) -> Unit,
    val disableAutomation: (String, String) -> Unit,
    val runAutomation: (String, String) -> Unit,
    val focusWorkspace: (String, Int) -> Unit,
    val setCloseWorkspace: (String, Int?) -> Unit,
    val closeWorkspace: (String, Int) -> Unit,
    val focusPane: (String, String) -> Unit,
    val setClosePane: (String, String?) -> Unit,
    val closePane: (String, String) -> Unit,
    val setRenamePane: (String, String?, String) -> Unit,
    val renamePane: (String) -> Unit,
)
